# Generated by Django 4.2.7 on 2023-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_transaction_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='wallet_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
